  - name: copying repo file
    copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  
  - name: Installing the rabbitmq-server
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: eanabling service and starting
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
  
  - name: create and provide permissions to user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present

